[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."media"]
  node_bundler = "nft"

[functions."verify-firebase"]
  node_bundler = "nft"


[[redirects]]
  from = "/api/flares"
  to = "/.netlify/functions/flares"
  status = 200

[[redirects]]
  from = "/api/media"
  to = "/.netlify/functions/media"
  status = 200

[[redirects]]
  from = "/api/like"
  to = "/.netlify/functions/like"
  status = 200

[[redirects]]
  from = "/api/report"
  to = "/.netlify/functions/report"
  status = 200

[[redirects]]
  from = "/api/admin/upload"
  to = "/.netlify/functions/admin-upload"
  status = 200

[[redirects]]
  from = "/api/admin/purge"
  to = "/.netlify/functions/admin-purge"
  status = 200

[[redirects]]
  from = "/api/admin/config"
  to = "/.netlify/functions/admin-config"
  status = 200

[[redirects]]
  from = "/api/flares/delete"
  to = "/.netlify/functions/delete-flare"
  status = 200

[[redirects]]
  from = "/api/support"
  to = "/.netlify/functions/support"
  status = 200

[[redirects]]
  from = "/api/firebase-config"
  to = "/.netlify/functions/firebase-config"
  status = 200

[[redirects]]
  from = "/api/verify/firebase"
  to = "/.netlify/functions/verify-firebase"
  status = 200

[[redirects]]
  from = "/api/profile/username"
  to = "/.netlify/functions/update-username"
  status = 200

[[redirects]]
  from = "/api/profile/avatar"
  to = "/.netlify/functions/update-avatar"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, x-admin-key"
