[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/flares"
  to = "/.netlify/functions/flares"
  status = 200

[[redirects]]
  from = "/api/like"
  to = "/.netlify/functions/like"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
